# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import testproto_pb2 as testproto__pb2


class TestprotoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFeature = channel.unary_unary(
        '/Testproto/GetFeature',
        request_serializer=testproto__pb2.Point.SerializeToString,
        response_deserializer=testproto__pb2.Feature.FromString,
        )


class TestprotoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFeature(self, request, context):
    """definition of method
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestprotoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFeature': grpc.unary_unary_rpc_method_handler(
          servicer.GetFeature,
          request_deserializer=testproto__pb2.Point.FromString,
          response_serializer=testproto__pb2.Feature.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Testproto', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
